### ISSUE TITLE
Implicit fallthroughs

### ISSUE THREAD

**Issue by r-barnes** [farsightsec/nmsg#153]
Are these implicit fallthroughs intentional? If so, can we mark them with `__attribute__((fallthrough))`? If not, can we fix the bugs with `break`?

https://github.com/farsightsec/nmsg/blob/a5a046b5db5b422d62a77618fc8188ffe3d72eb4/libmy/b64_decode.c#L37

https://github.com/farsightsec/nmsg/blob/a5a046b5db5b422d62a77618fc8188ffe3d72eb4/libmy/b64_decode.c#L48

https://github.com/farsightsec/nmsg/blob/a5a046b5db5b422d62a77618fc8188ffe3d72eb4/libmy/b64_decode.c#L60

https://github.com/farsightsec/nmsg/blob/a5a046b5db5b422d62a77618fc8188ffe3d72eb4/libmy/b64_decode.c#L72

**Comment by cmikk** [comment]
Yes, these are intentional, and idiomatic C for this situation. Adding `break` statements will break the logic of this loop, quite severely.

In contrast, `__attribute__((fallthrough))` is nonstandard and not entirely portable, and will trade the implicit fallthrough warning for an unknown attribute warning on those compilers which have not adopted this extension, or worse for the rarer compliers which haven't adopted the `__attribute__((foo))` extension syntax.

The proper way to address the implicit fallthrough warnings, IMO, is to turn them off after verifying that none of the warning sites were a missed `break`.

I will accept your related pull request, though, as the implicit fallthrough it addresses is not needed.
